name: suave-jupyter-environment
channels:
  - conda-forge
  - trentonoliphant
  - mlgill
dependencies:
  - python
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas==0.24
  - partd
  - bokeh
  - dask
  - ipywidgets
  - owslib
  - geojson
  - shapely
  - geopandas
  - geojsonio
  - tensorflow
  - tensorflow-gpu
  - scikit-learn
  - panel
  - holoviews
  - hvplot
  - datashader
  - keras
  - pip
  - pip:
    - imutils
    - clarifai
    - spacy
    - tqdm
    - opencv-python-headless
    - opencv-contrib-python-headless
    - git+https://github.com/explosion/spacy-models@en_core_web_sm-2.2.5#egg=en_core_web_sm
